### ISSUE TITLE
[BUG] Error No.17 -> RedWarden tries to start listener twice

### ISSUE THREAD

**Issue by 0xShkk** [mgeeky/RedWarden#11] opened 2021-11-25 06:41 UTC
Hi,

thank you for this great tool and your support to the community!

I played around with it today to see if it can be used in my next assessment.
I have noticed two bugs while doing so.

Lets start with the first here.

When starting, RedWarden always tries to start 2 listeners even if only one listener is defined at the config while.
Basically the same as [https://github.com/mgeeky/RedWarden/issues/3#issue-935316665](url) but the tool works as expected. However, the core bug seems not to be solved as I 100% have only one listener defined at my config file.

**Comment by mgeeky** [comment] 2021-11-25 15:28
Hi, 

Thanks for this bug request. Currently I'm on the vacations with a greatly limited access to my computer. Will see what I can do in upcoming days, or will get back to this one in late december. 

Thank you for your time to spent to report this one, nice catch!

Regards,
Mariusz

**Comment by mgeeky** [comment] 2022-08-23 23:11
So, I'm unable to reproduce the issue while having a single listener defined. 

@ptr0x1 was kind enough to mention the same issue and propose a hefty workaround for this should anyone else also experience it:
[See Peter's workaround here](https://github.com/mgeeky/RedWarden/pull/20)

Since I cannot trigger the bug, I'm not sure how to proceed here.

**Comment by mgeeky** [comment] 2022-09-29 22:28
Closing it now due to lack of further communication. Should the problem remain - feel free to reopen the issue and provide me with more context to analyse it :-)

**Closed by mgeeky** 2022-09-29 22:28 UTC
